{
 "title": "Dashboard 3 - Status des services critiques",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "DS_PROMETHEUS", "label": "Data Source", "query": "prometheus" },
   {
    "name": "hostname",
    "label": "Hostname",
    "query": {
     "query": "label_values(node_service_status, hostname)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "SSH Service",
   "type": "stat",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_service_status{hostname=\"$hostname\",service=\"ssh\"}",
     "legendFormat": "SSH"
    }
   ]
  },
  {
   "title": "CRON Service",
   "type": "stat",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_service_status{hostname=\"$hostname\",service=\"cron\"}",
     "legendFormat": "CRON"
    }
   ]
  },
  {
   "title": "Docker Service",
   "type": "stat",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_service_status{hostname=\"$hostname\",service=\"docker\"}",
     "legendFormat": "DOCKER"
    }
   ]
  },
  {
   "title": "Nb running services",
   "type": "stat",
   "gridPos": { "h": 6, "w": 12, "x": 5, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(node_service_status{hostname=\"$hostname\"} == 1)",
     "legendFormat": "Nb running services"
    }
   ]
  }
 ]
}